name: Swift Codecov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-coverage:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests and collect coverage
        working-directory: ./mobile
        run: swift test --enable-code-coverage

      - name: Upload report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: ./mobile